---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/flavorjones/mini_portile
    branch: master
jobs:
- name: Ruby
  plan:
  - get: repo
  - task: With version 1.9.3
    config:
      platform: linux
      image: docker:///ruby#1.9.3
      inputs:
      - name: repo
      run:
        path: bash
        args:
        - "-c"
        - cd repo && bundle install && rake
    privileged: false
  - task: With version 2.0
    config:
      platform: linux
      image: docker:///ruby#2.0
      inputs:
      - name: repo
      run:
        path: bash
        args:
        - "-c"
        - cd repo && bundle install && rake
    privileged: false
  - task: With version 2.1
    config:
      platform: linux
      image: docker:///ruby#2.1
      inputs:
      - name: repo
      run:
        path: bash
        args:
        - "-c"
        - cd repo && bundle install && rake
    privileged: false
  - task: With version 2.2
    config:
      platform: linux
      image: docker:///ruby#2.2
      inputs:
      - name: repo
      run:
        path: bash
        args:
        - "-c"
        - cd repo && bundle install && rake
    privileged: false
  - task: With version jruby-1.7.23
    config:
      platform: linux
      image: docker:///jruby#1.7.23
      inputs:
      - name: repo
      run:
        path: bash
        args:
        - "-c"
        - cd repo && bundle install && rake
    privileged: false
  - task: With version jruby-9.0.4.0
    config:
      platform: linux
      image: docker:///jruby#9.0.4.0
      inputs:
      - name: repo
      run:
        path: bash
        args:
        - "-c"
        - cd repo && bundle install && rake
    privileged: false
