---
install:
  - ps: |
      if ($env:ruby_version -like "*head*") {
        $(new-object net.webclient).DownloadFile("https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-head/rubyinstaller-$env:ruby_version.exe", "$pwd/ruby-setup.exe")
        cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby$env:ruby_version
      }
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET MAKE=make -j2
  - ruby --version
  - gem --version
  - gem install "bundler:~>2.1" --conservative
  - bundle install
  - gpg --version
  - ridk enable
  - pacman -S --noconfirm %MINGW_PACKAGE_PREFIX%-cmake

build: off

test_script:
  - bundle exec rake

environment:
  matrix:
    - ruby_version: head-x64
    - ruby_version: "24"
    - ruby_version: "26-x64"
