% require "common_prelude.rb"

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
<%= erbify_file "common_resources.yml" -%>
  - name: mini-portile-pr
    type: pull-request
    icon: github
    check_every: 5m
    # https://ci.nokogiri.org/api/v1/teams/nokogiri-core/pipelines/mini-portile-pr/resources/mini-portile-pr/check/webhook?webhook_token=((webhook_token))
    webhook_token: ((mini-portile-pr-webhook-token))
    source:
      repository: flavorjones/mini_portile
      access_token: ((github-repo-status-access-token))
      ignore_paths: <%= $common_ignore_paths %>

jobs:
  - name: pr-pending
    public: true
    plan:
      - get: ci
      - get: mini-portile-pr
        trigger: true
        version: every
      - put: mini-portile-pr
        params: {path: mini-portile-pr, status: PENDING}

% RUBIES[:mri].last(2).each do |ruby_version|
  - name: ruby-<%= ruby_version %>-pr
    public: true
    serial_groups: [pr]
    plan:
      - get: ci
      - get: mini-portile-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: mini-portile-pr
              path: mini-portile
          run:
            path: ci/concourse/tasks/rake-test/task.sh
        on_failure:
          put: mini-portile-pr
          params: {path: mini-portile-pr, status: FAILURE}
% end

  - name: pr-success
    public: true
    serial_groups: [pr]
    disable_manual_trigger: true
    plan:
      - get: mini-portile-pr
        trigger: true
        version: every
        passed:
% RUBIES[:mri].last(2).each do |ruby_version|
          - ruby-<%= ruby_version %>-pr
% end
      - put: mini-portile-pr
        params: {path: mini-portile-pr, status: SUCCESS}
