name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  schedule:
    - cron: "0 8 * * 5" # At 08:00 on Friday # https://crontab.guru/#0_8_*_*_5
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.3", "2.4", "2.5", "2.6", "2.7", "3.0", "head"]

    steps:
      - uses: actions/checkout@v2
      - uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          apt-get: _update_ build-essential cmake
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
